[toolchain]
channel = "nightly-2025-05-06"
components = ["cargo", "clippy", "rustfmt", "rust-src"]
targets = [
    "aarch64-unknown-linux-gnu",
    "thumbv7neon-unknown-linux-gnueabihf",
    "target.armv7-unknown-linux-gnueabihf"
]
